// Copyright 2018 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_ota_control                     21
#define gattdb_temperature_measurement         24
#define gattdb_tx_power_level                  28
#define gattdb_battery_level                   31
#define gattdb_characteristic_presentation_format         32
#define gattdb_light                           36
#define gattdb_Ultra                           41
#define gattdb_count                           46
#define gattdb_alert                           51

#endif
